<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<li>
<!-- Modal -->
<div id="checkbookWrapper">
<div class="modal-dialog">
<div class="modal-content">
<section id="senderInfo">
<div class="container">
<div class="row">
<div>
<div class="box" style="margin: 0; padding: 0px 20px 0px 20px;">
<h3 class="bigintro">Pay by Online Check</h3>
<div id="senderSection" style="position: absolute; top:35px;background-repeat:no-repeat;min-height: 300px;width: 100%;background-image: url('http://checkbook.io/static/img/blue_check.jpg');
background-position: 0px 20px;">

	<a style="position: absolute; bottom: 13px; font-size: 12px;" href="https://www.checkbook.io/api/terms" target="_blank" onclick="return popitup('https://www.checkbook.io/api/terms')">Terms & conditions</a>
	<a style="position: absolute; bottom: 13px; left: 305px; text-align: right; font-size: 12px;" target="_blank" href="https://www.checkbook.io/api/security" onclick="return popitup('https://www.checkbook.io/api/security')">Security: Bank info is not saved on our site.</a>

<div id="enterRoutingMsg" style="display: none; position: absolute; left: 5px; top: 275px;color: red;">
You are almost there. Please provide your routing # and account #.
</div>

<div id="senderCheckUI">

<div style="position: relative;top: 20px;">
<div style="font-family: Helvetica,Arial,sans-serif;">
<div id="displayName" style="position: absolute; left: 20px; top: 14px;"></div>
<!--<div id="displayAddress" style="font-size: 70%; position: absolute; left: 10px; top: 28px;">&nbsp;&nbsp;&nbsp;Addr1, Addr2</div>-->
<!--<div id="displayAddressAdditional" style="font-size: 70%; position: absolute; left: 10px; top: 39px;">&nbsp;&nbsp;&nbsp;JR_City,&nbsp;CA&nbsp;76001</div>-->
	<div id="displayEmail" style="font-size: 9px; position: absolute; left: 20px; top: 58px;"></div>
        <div id="addressLine1" style="font-size: 9px; position: absolute; left: 20px; top: 38px;"></div>
	<div id="cityStateZip" style="font-size: 9px; position: absolute; left: 20px; top: 48px;"></div>
<div style="position: absolute; left: 400px; top: 12px"></div>
</div>
<div id="displayDate" style="position: absolute; left: 330px; top: 50px">10-14-2013</div>
<div id="displayRecipient" style="position: absolute; left: 90px; top: 82px; font-size: 125%"></div>
<div id="displayValue" style="position: absolute; left: 440px; top: 90px; font-size: 125%"></div>
<div id="displayWrittenOutSum" style="font-style: italic; font-size: 16px; position: absolute; left: 40px; top: 116px; width:400px;"></div>
<div id="displayRecurrence" style="font-weight: bold; position: absolute; left: 435px; top: 250px; width: 110px; word-wrap: line-break"></div>
<div id="displayFor" style="font-family: Helvetica,Arial,sans-serif; font-size: 120%; position: absolute; left: 50px; top: 168px; width:250px; height:40px; overflow:hidden"></div>
<div id="displayNameTrailer" style="font-size: 125%; font-style: italic; position: absolute; left: 309px; top: 168px; width: 215px; height: 40px;"></div>
<div style="position: absolute; left: 45px; top: 215px">
<input type="text" style="border-color: blue; font-weight: bold;border: 2px solid #4987CA;height: 28px;top: -15px;position: relative; padding-left: 5px !important; background: #eee; padding: 0;" maxlength="9" size="9"
id="routingNumber" name="routingNumber" placeholder="Routing #"
data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Enter Your Routing Number">
</div>
<div style="position: absolute; left: 220px; top: 215px">
<input type="text" style="border-color: blue; font-weight: bold;border: 2px solid #4987CA;height: 28px;top: -15px;left: -50px;position: relative; background: #eee; padding: 0; padding-left: 5px !important;" maxlength="17" size="17"
id="accountNumber" name="accountNumber" placeholder="Account #"
data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Enter Your Account Number">
</div>

</div>	
</div>


<div class="form-group rightSideSenderForm" style="padding-right: 20px; margin-right:10px; margin-top:20px;">

<!--<span style="position: absolute; top:-40px;">------------- OR -------------</span>-->
<div id="showReviewDiv">

</div>

<div id="sendACheck" style="padding:10px 20px 10px 20px; display: none;">
You are ready to submit a Check payment of $<span class="netAmount"></span> to <span class="merchantName"></span>.
<br><br>
The money will be withdrawn from your bank account.
<br>
<br>
<div class="errorResp"></div>
<br>	
<button type="button" id="sendCheckBtn" class="btn btn-success" tabindex="5"
style="margin-bottom: 10px;">
Send the Check</button>

<!--Show throbber-->
<div id="throbberIdSendCheck" class="progress progress-striped active" style="display: none;">
<div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
<!--<span class="sr-only">45% Complete</span>-->
</div>
</div>
</div>

<div id="bankVerification" style="padding:0px 20px 10px 20px; display: none;">
<div id="bankAuth" style="margin-top:-13px;">
                                                                    <strong class="verificationTitle" style="display: none"></strong>
                                                                    <div class="bankSelect">
                                                                        <div class="row ctrls">
                                                                            <ul class="nav nav-tabs navTab">
                                                                              <li class="active"><a href="#bankVerify">Bank Verification</a></li>
                                                                              <!--<li class=""><a href="#microVerify">Microdeposit</a></li> -->
                                                                            </ul>
                                                                            <div class="tab-content">
                                                                                <div class="tab-pane active" id="bankVerify">
                                                                                    <select id="bank_name" name="bank_name" class="margTB15 form-control"  style="margin: 20px 0px 15px 0px !important;">
                                                                                        <option value="0" selected="">Choose your bank</option>
                                                                                        <option value="bofa">Bank Of America</option>
                                                                                        <option value="wells">Wells fargo</option>
                                                                                        <option value="chase">Chase</option>
											<option value="citi">Citi</option>
											<option value="us">US Bank</option>
                                                                                        <option value="micro">My Bank is not listed here</option>
                                                                                    </select>
                                                                                    
                                                                                    <!-- LOGIN -->
                                                                                    <div id="bankAuthCheckDiv">
                                                                                          <div class="form-group">
                                                                                                <i class="icon-user box_i"></i>
                                                                                                <input id='bank_user' name='bank_user' type="email" class="form-control" id="username" style="margin:0px 0px 15px 0px !important; padding-left:30px !important;"
                                                                                                    placeholder="Your Bank Username" disabled="disabled">
                                                                                          </div>
                                                                                          <div class="form-group" style="padding-bottom:0px; margin-bottom:0px;">
                                                                                                <i class="icon-lock box_i"></i>
                                                                                                <input id='bank_passwd' name='bank_passwd' type="password" class="form-control padLeft20" id="password" style="margin:0px 0px 15px 0px !important; padding-left:30px !important;"
                                                                                                    placeholder="Your Bank password" disabled="disabled">
                                                                                                <p class="errorResp" style="margin-bottom:5px;"></p>
                                                                                          </div>
                                                                                          <button id="bankAuthCheck" type="button" class="btn btn-danger" disabled="disabled">Login</button>
                                                                                          <div id="throbberIdBankAuthCheck" class="progress progress-striped active" style="display: none;">
                                                                                                    <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                                                                                      <!--<span class="sr-only">45% Complete</span>-->
                                                                                                    </div>
                                                                                            </div>
                                                                                    </div>
                                                                                    <!--/LOGIN -->
                                                                                </div>
                                                                                
                                                                                <div class="tab-pane" id="microVerify">
                                                                                    <div id="microAuthInputDiv">
                                                                                            <div class="form-group">
                                                                                                <input class="form-control" type="text" style="margin:15px 0px 15px 0px !important; padding-left:10px !important;"
                                                                                                id="accountNum" name="accountNum" placeholder="Account Number" maxlength="20"
                                                                                                data-rule-number="true" data-rule-required="true" data-msg-required="Enter your Account number">
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <input class="form-control" type="text" style="margin:0px 0px 15px 0px !important; padding-left:10px !important;"
                                                                                                id="routingNum" name="routingNum" placeholder="Routing Number"
                                                                                                data-toggle="tooltip" data-placement="bottom" title=""
                                                                                                data-msg-range="Routing number needs to be 9 digit long"
                                                                                                data-rule-number="true"
                                                                                                data-rule-required="true"
                                                                                                data-msg-required="Enter Your Routing Number"
                                                                                                data-rule-maxlength="9" data-rule-minlength="9" maxlength="9">
                                                                                                    
                                                                                                <p class="errorResp"></p>
                                                                                            </div>
                                                                                            <button type="button" id="microAuthInputBtn" class="btn btn-danger">Submit</button>
                                                                                    </div>
                                                                                    
                                                                                    
                                                                                    <div id="microAuthVerifyDiv" style="display: none;">
                                                                                        
                                                                                            <div class="form-group">
                                                                                                <input class="form-control" type="text" style="margin:15px 0px 15px 0px !important; padding-left:10px !important;" maxlength="9"
                                                                                                id="accountNum" name="accountNum" placeholder="Enter amount"
                                                                                                data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Enter Your Account Number">	
                                                                                            </div>
                                                                                            <div class="form-group">
                                                                                                <input class="form-control" type="text" style="margin:0px 0px 15px 0px !important; padding-left:10px !important;"
                                                                                                id="routingNum" name="routingNum" placeholder="Enter amount"
                                                                                                data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Enter Your Routing Number">	<p class="errorResp"></p>
                                                                                            </div>
                                                                                            <button type="button" id="microAuthCheck" class="btn btn-danger">Submit</button>
                                                                                                      
                                                                                    </div>
                                                                                    
                                                                                </div>
                                                                
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                
                                                                    
                                                                    <!-- MFA TOKEN -->
                                                                    <div id="bankMfaCheckDiv" style="display: none;">
                                                                        
                                                                          <div class="form-group">
                                                                                <span class="font-bold">Security Question By <span class="bankNameId"></span></span>
                                                                                <p class="padTB15">
                                                                                    <span class="mfa_que"></span>
                                                                                </p>
                                                                          </div>
                                                                          <div class="form-group">
                                                                                <input id='mfa_answer' name='mfa_answer' type="text" class="form-control" style="margin:0px 0px 15px 0px !important; padding-left:30px !important;"
                                                                                    placeholder="Your answer">
                                                                                <p class="errorResp"></p>
                                                                          </div>
                                                                          
                                                                            <button id="bankMfaCheck" type="button" class="btn btn-danger">Submit</button>
                                                                            <div id="throbberIdBankMfaCheck" class="progress progress-striped active" style="display: none;">
                                                                                    <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                                                                      <!--<span class="sr-only">45% Complete</span>-->
                                                                                    </div>
                                                                            </div>
                                                                        
                                                                    </div>
                                                                    <!--/MFA TOKEN -->
                                                                    
                                                                    
                                                                    <!-- ENTER YOUR ACCOUNT NUMBER-->
                                                                    <div id="enterAcctNumDiv" style="display: none; padding-top: 15px;">
                                                                        Thank you, <br>
                                                                        Your account is Verified,<br><br>
                                                                        We have confirmed your account number, please continue to next step. <br><br>
                                                                        Account Number: <span class="acctNum"></span>
                                                                        
                                                                        <div style="margin-top: 15px;">
                                                                            <button id="enterAcctNumButton" type="button" class="btn btn-danger">Complete</button>
                                                                        </div>
                                                                    </div>
                                                                    <!--/MFA TOKEN -->
                                                                    
                                                                    
                                                                    
                                                                </div>
</div>



<div id="setUpYourPin" style="padding:10px 20px 10px 20px; display: none;">
Please choose a PIN of minimum 6 digits incase you wish to use this account again
<br>
<br>

<input type="password" class="form-control inputCB" id="online_passcode" name="online_passcode"
placeholder="Enter Pin" tabindex="1" style="margin-bottom: 15px;"
data-parsley-maxlength="26" 
data-parsley-minlength="6"
data-parsley-required="true">

<input type="password" class="form-control inputCB" id="online_passcode_confirm" name="online_passcode_confirm"
placeholder="Confirm Pin" tabindex="2" style="margin-bottom: 15px;"	
data-parsley-maxlength="26" 
data-parsley-minlength="6"
data-parsley-required="true"
data-parsley-equalto="#online_passcode">	


<!--<span>You are ready to submit a Check payment of <span class="netAmount"></span> to <span class="merchantName">
</span>.
The money will be withdrawn from your bank account.
</span>
-->


<div class="errorResp" style="display: none; color: red;">	
</div>

<button type="button" id="pinCreateBtn" class="btn btn-danger" tabindex="5"
style="margin-bottom: 10px; margin-top:12px;">
Continue</button>



<!--Show throbber-->
<div id="throbberIdVerify" class="progress progress-striped active" style="display: none;">
<div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
<!--<span class="sr-only">45% Complete</span>-->
</div>
</div>
</div>



<div id="loginWithYourPin" style="padding:5px 20px 10px 20px; display: none;">

You transacted with us earlier. Simply enter your PIN
<br><br>
<i class="icon-envelope" style="top:80px;"></i>
<input type="email" class="form-control" placeholder="Email Address" id="senders_email_id_exist" style="padding-left:30px !important; clear:both;"
tabindex="3" data-parsley-required="true">

<input type="password" class="form-control inputCB" id="online_passcode_exist" name="online_passcode_exist"
placeholder="Enter Pin" tabindex="1" style="margin-bottom: 15px; padding-top:5px;"
data-parsley-required="true">

<div id="invalidPinLoginMsg" style="display: none; color: red; padding-bottom: 7px;">
Invalid Pin
</div>

<button type="button" id="loginWithYourPinBtn" class="btn btn-danger" tabindex="5"
style="margin-bottom: 10px;">
Continue</button>



<!--Show throbber-->
<div id="throbberIdVerifyLogin" class="progress progress-striped active" style="display: none;">
<div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
<!--<span class="sr-only">45% Complete</span>-->
</div>
</div>

</div>

</div>


</div>
<!--Show throbber-->
<div id="throbberIdSender" class="progress progress-striped active" style="display: none;">
<div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
<!--<span class="sr-only">45% Complete</span>-->
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<!--/LOGIN -->	
</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

<li>
	<input type="hidden" name="payment[token]" id="checkbook_token" value=""/>
	<input type="hidden" name="payment[amount]" value="<?php echo $this->getFinalValue(); ?>"/>
	<input type="hidden" name="payment[currency]" value="<?php echo $this->getCurrencyCode();?>"/>
	<input type="hidden" name="payment[description]" value="<?php echo $this->getItemDescription(); ?>"/>
	
<script type="text/javascript">
var checkbook_config = {
	data_key: "<?php echo $this->getMethod()->getConfigData('publishable_key');?>",
	data_amount: "<?php echo $this->getFinalValue(); ?>",
	data_name: "Your Company Name",
	data_for: "Your Company Name",
	data_description: "<?php echo $this->getItemDescription(); ?>",
	data_user_email: "<?php echo $this->getCustomerEmail(); ?>",
	data_firstName : "<?php echo $this->getCustomerFirstName(); ?>",
	data_lastName : "<?php echo $this->getCustomerLastName(); ?>",
	data_addr1 : "<?php echo $this->getStreetLine1(); ?>",
	data_addr2 : "<?php echo $this->getStreetLine2(); ?>",
	data_city : "<?php echo $this->getCity(); ?>",
	data_state : "<?php echo $this->getRegion(); ?>",
	data_zip : "<?php echo $this->getPostcode(); ?>",
	data_country : "<?php echo $this->getCountryName(); ?>",
        data_env : "sandbox"
};
var checkbook = new Checkbook(checkbook_config);



function popitup(url) {
			newwindow=window.open(url,'name','height=500,width=500');
			if (window.focus) {newwindow.focus()}
			return false;
		}

</script>
<div>
  <?php echo $this->getMethod()->getConfigData('message');?>
</div>
</li>
</ul>
